function createArmFigure(X1, Y1, Z1)
%CREATEFIGURE(X1, Y1, Z1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Z1:  vector of z data

%  Auto-generated by MATLAB on 07-Sep-2018 21:58:12

% Create figure
figure1 = figure('Name','Robotic Arm Stickplot');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot3
plot3(X1,Y1,Z1,'DisplayName','Robot Links','MarkerFaceColor',[1 0 0],...
    'MarkerEdgeColor',[0 0 0],...
    'MarkerSize',10,...
    'Marker','square',...
    'LineWidth',4,...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);

% Create xlabel
xlabel({'X-Distance(mm)'});

% Create zlabel
zlabel({'Z-Distance(mm)'});

% Create title
title({'Robotic Arm Stickplot'});

% Create ylabel
ylabel({'Y-Distance(mm)'});

view(axes1,[-37.5 30]);
% Create legend
legend(axes1,'show');

